### ISSUE TITLE
Make heading h2 instead of h3

### ISSUE THREAD

**Issue by paulcreek** [dsifford/academic-bloggers-toolkit#284]
Is it possible to change the heading of the bibliography from h3 to h2?

In my pages I use h2 for all sections, and this way unfortunately the bibliography appears as a subsection of the last section.

Thanks, and thanks for the great plugin.

**Comment by dsifford** [comment]
Hi @paulcreek, I appreciate you taking the time to post your issue in this location.

To be honest, the "heading" option for the plugin is pretty much a vestigial structure at this point. I don't personally use it because it's both easier and IMHO better to do it with CSS because the changes to your heading can apply both pro and retroactively.

So, in short, what I'd recommend doing is removing the heading option entirely and instead add this bit of CSS to your stylesheet (adjusting to fit your site's style and the font size that you'd like it to be).

```css
#abt-bibliography {
    background: #f9f9f9;
    border-radius: 2px;
    font-size: 0.8em;
    padding: 0 10px 10px 10px;
}
#abt-bibliography::before {
    content: 'References';
    font-size: 1.3rem;
    line-height: 2.5em;
}
```

The only caveat to this is that it won't work with the "toggle" option (which is also vestigial at this point).

Let me know if that solves your problem.
