### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by cwbullet** [dsifford/academic-bloggers-toolkit#285]
**ABT Version:** 4.9.2

**PHP Version:** 5.6

**Theme:**MH New Desk

**Plugin List:**
- All turn off but tool kit.

 Safari, firefox

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**

**Actual behavior:**  http://walkingoffpounds.com/weight-loss-tip-avoid-the-couch-potatoes/
The background color for the bibliography does not load.  I have tried turn off all plugins and several themes.  It never loads.  The rest of the CSS changes, not the background color.  

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
@cwbullet Can you share the CSS that you have that attempts to set the background color?

**Comment by cwbullet** [comment]
.abt-tooltip {
    background-color: teal;
    color: white;
    border: dashed gold 2px;
}

.abt-tooltip a {
    color: gold;
}

.abt-tooltip a:hover {
    color: yellow;
}

.abt-tooltip__callout_up {
    border-color: transparent transparent teal;
}

.abt-tooltip__callout_down {
    border-color: teal transparent transparent;
}

.abt-tooltip__close-button {
    color: teal;
    background: gold;
}

**Comment by dsifford** [comment]
@cwbullet All of those selectors are for just the tooltip styles.

To style your bibliography, check out the middle example in the settings page.

For convenience, here's the CSS that you'll find in that example:

```css
.abt-bibliography {
    background: teal;
}

.abt-bibliography__heading {
    color: gold;
    text-shadow: 1px 1px 1px #444
}

.abt-bibliography__container > div {
    font-size: 0.8em;
    color: white;
}

.abt-bibliography__container > div a {
    color: gold;
}

.abt-bibliography__container > div a:hover {
    color: yellow;
}

.csl-left-margin {
    color: gold;
}
```

For your specific case, if all you want to do is simply change the background of your bibliography, just add this to your stylesheet (changing out the color value for whatever color you prefer).

```css
.abt-bibliography {
    background: #efefef;
}
```

Hope that helps!
